version: '3.7'

services:
  project:
    build: .
    container_name: "project_training"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    
